%RUN_MAIN_SPINODAL_GNN_PREP Minimal runnable script entrypoint.
%
% Edit inpPath/csvPath/options below, then run this script by typing:
%
%   run_main_spinodal_gnn_prep

moduleRoot = fileparts(mfilename('fullpath'));
addpath(moduleRoot);
addpath(genpath(fullfile(moduleRoot, 'src')));

% Example defaults (project-specific sample).
matlabRoot = fileparts(moduleRoot);
inpPath = fullfile(matlabRoot, 'results', 'sheets', 'lamellar', ...
    'sheetCone_tr50_ang000_lamellar_N128_1x1', 'FEA_shell', 'sheet_shell_shell_job.inp');
csvPath = fullfile(matlabRoot, 'results', 'sheets', 'lamellar', ...
    'sheetCone_tr50_ang000_lamellar_N128_1x1', 'FEA_shell', 'midplane_results_shell.csv');

outputs = main_spinodal_gnn_prep(inpPath, csvPath, ...
    'ElsetName', 'SPINODAL_SHELL', ...
    'StructuralDetailLevel', 0.3, ...
    'PlotStyle', 'paper2d', ...
    'PlotBoundaryMode', 'interior', ...
    'MakeThicknessPlot', false, ...       % true/false avhengig av om man vil ha med tykkelse
    'PlotUnitsScale', 1, ...              % keep native coordinate scale
    'PlotXLabel', 'x [mm]', ...
    'PlotYLabel', 'y [mm]', ...
    'PlotNodeMarkerSize', 2.6, ...
    'PlotBoundaryMarkerSize', 2.8, ...
    'OutDir', fullfile(moduleRoot, 'out'), ...
    'Prefix', 'run_main');

disp(outputs.exports);
