%RUN_MAIN_SPINODAL_GNN_PREP_FROM_INP Minimal INP-only test entrypoint.
%
% Edit inpPath/options below, then run:
%   run_main_spinodal_gnn_prep_from_inp

moduleRoot = fileparts(mfilename('fullpath'));
addpath(moduleRoot);
addpath(genpath(fullfile(moduleRoot, 'src')));

% Example defaults (project-specific sample).
matlabRoot = fileparts(moduleRoot);
inpPath = fullfile(matlabRoot, 'results', 'sheets', 'lamellar', ...
    'sheetCone_tr50_ang045_lamellar_N128_1x1', 'sheet_shell.inp');

outputs = main_spinodal_gnn_prep_from_inp(inpPath, ...
    'ElsetName', 'SPINODAL_SHELL', ...
    'StructuralDetailLevel', 0.3, ...
    'StructuralMinIslandNodes', 1, ...
    'MakePlots', true, ...
    'SavePlots', true, ...
    'PlotUnitsScale', 1, ...
    'PlotXLabel', 'x [mm]', ...
    'PlotYLabel', 'y [mm]', ...
    'OutDir', fullfile(moduleRoot, 'out'), ...
    'Prefix', 'run_main_inp');

disp(outputs.exports);
