%EXAMPLE_COMPARE_DOWNSAMPLE_METHODS Compare deterministic downsampling modes.

thisDir = fileparts(mfilename('fullpath'));
moduleRoot = fileparts(thisDir);
matlabRoot = fileparts(moduleRoot);

addpath(moduleRoot);
addpath(genpath(fullfile(moduleRoot, 'src')));

inpPath = fullfile(matlabRoot, 'results', 'sheets', 'lamellar', ...
    'sheetCone_tr50_ang000_lamellar_N128_1x1', 'FEA_shell', 'sheet_shell_shell_job.inp');
csvPath = fullfile(matlabRoot, 'results', 'sheets', 'lamellar', ...
    'sheetCone_tr50_ang000_lamellar_N128_1x1', 'FEA_shell', 'midplane_results_shell.csv');

outDir = fullfile(moduleRoot, 'out');
methods = {'farthest', 'grid', 'hybrid'};
allOutputs = cell(numel(methods), 1);

for i = 1:numel(methods)
    method = methods{i};
    runName = sprintf('compare_%s', method);
    allOutputs{i} = main_spinodal_gnn_prep(inpPath, csvPath, ...
        'ElsetName', 'SPINODAL_SHELL', ...
        'DetailLevel', 0.10, ...
        'DownsampleMethod', method, ...
        'HybridAnchorFraction', 0.35, ...
        'BoundaryKeepRatio', 0.65, ...
        'BoundaryStraightTolDeg', 8, ...
        'DownsampleOutputMode', 'mesh', ...
        'OutDir', outDir, ...
        'RunName', runName, ...
        'Prefix', 'compare_methods');

    fprintf('Method %s -> %s\n', method, allOutputs{i}.run_dir);
end

% Experimental vertical-midpoint representation (separate from standard pipeline).
hybridIdx = find(strcmp(methods, 'hybrid'), 1);
if isempty(hybridIdx)
    hybridIdx = numel(allOutputs);
end
baseOutput = allOutputs{hybridIdx};

midExpGraph = downsample_midpoint_experimental(baseOutput.downsampled_mesh_graph, ...
    'UseInteriorBoundaryOnly', true, ...
    'ColumnStride', 5, ...
    'PairMode', 'extremes', ...
    'ComponentKeepRatio', 0.04, ...
    'MaxNodesPerComponent', 4, ...
    'MinNodesPerComponent', 2);
midExpDir = fullfile(baseOutput.run_dir, 'midpoint_experimental');
midExpDataDir = fullfile(midExpDir, 'data');
midExpPlotDir = fullfile(midExpDir, 'plots');
if ~isfolder(midExpDataDir)
    mkdir(midExpDataDir);
end
if ~isfolder(midExpPlotDir)
    mkdir(midExpPlotDir);
end

midExpPaths = export_graph_csv(midExpGraph, midExpDataDir, 'midpoint_experimental_graph');

figMidExp = figure('Name', 'Experimental Midpoint Graph');
axMidExp = axes('Parent', figMidExp);
plot_graph_mesh(midExpGraph, ...
    'AxesHandle', axMidExp, ...
    'Title', 'Experimental Midpoint Graph', ...
    'Style', 'paper2d', ...
    'BoundaryMode', 'none', ...
    'UnitsScale', 1, ...
    'XLabel', 'x [mm]', ...
    'YLabel', 'y [mm]', ...
    'NodeMarkerSize', 2.8);
saveas(figMidExp, fullfile(midExpPlotDir, 'midpoint_experimental_graph.png'));

comparison = struct();
comparison.standard_methods = methods;
comparison.standard_outputs = allOutputs;
comparison.midpoint_experimental_graph = midExpGraph;
comparison.midpoint_experimental_exports = midExpPaths;
disp(comparison);
